version: '3'

services:
  app:
    build:
      context: ./developer-extension-hub-client
    ports:
      - '3000:3000'
    volumes:
      - ./developer-extension-hub-client:/app
    depends_on:
      - server

  server:
    build:
      context: ./developer-extension-hub-server
    ports:
      - '3001:3001'
    volumes:
      - ./developer-extension-hub-server:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
